/*
 * Recipe Tracker - OpenAPI 3.0
 *
 * This is a simple API for keeping track of recipes and their ingredients. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Model;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Swashbuckle.AspNetCore.Annotations;

namespace IO.Swagger.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class RecipeApiController : ControllerBase
    {
        /// <summary>
        /// Create a new recipe.
        /// </summary>
        /// <remarks>Create a new recipe.</remarks>
        /// <param name="body">The new recipe to create.</param>
        /// <response code="201">Successfully created recipe.</response>
        /// <response code="400">Bad Request</response>
        [HttpPost]
        [Route("/recipe")]
        [SwaggerOperation("CreateRecipe")]
        public virtual IActionResult CreateRecipe([FromBody] Recipe body)
        {
            //TODO: Uncomment the next line to return response 201 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(201);

            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400);

            throw new NotImplementedException();
        }

        /// <summary>
        /// Delete a recipe by Id.
        /// </summary>
        /// <remarks>Delete a recipe by its Id.</remarks>
        /// <param name="id"></param>
        /// <response code="202">Successfully deleted recipe.</response>
        [HttpDelete]
        [Route("/recipe/{id}")]
        [SwaggerOperation("DeleteRecipeById")]
        public virtual IActionResult DeleteRecipeById([FromRoute][Required] int? id)
        {
            //TODO: Uncomment the next line to return response 202 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(202);

            throw new NotImplementedException();
        }

        /// <summary>
        /// Get a recipe by Id.
        /// </summary>
        /// <remarks>Get a recipe by its Id.</remarks>
        /// <param name="id"></param>
        /// <response code="200">Successfully found recipe.</response>
        /// <response code="404">Recipe not found</response>
        [HttpGet]
        [Route("/recipe/{id}")]
        [SwaggerOperation("GetRecipeById")]
        [SwaggerResponse(statusCode: 200, type: typeof(Recipe), description: "Successfully found recipe.")]
        public virtual IActionResult GetRecipeById([FromRoute][Required] int? id)
        {
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(Recipe));

            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404);
            string exampleJson = null;
            exampleJson = "{\n  \"dateCreated\" : \"2000-01-23T04:56:07.000+00:00\",\n  \"name\" : \"Chicken Tikka Masala\",\n  \"ingredients\" : [ {\n    \"amount\" : \"todo\",\n    \"name\" : \"Milk\"\n  }, {\n    \"amount\" : \"todo\",\n    \"name\" : \"Milk\"\n  } ],\n  \"id\" : 0,\n  \"source\" : \"From Crook to Crook\",\n  \"labels\" : [ {\n    \"name\" : \"Breakfast\"\n  }, {\n    \"name\" : \"Breakfast\"\n  } ]\n}";

            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<Recipe>(exampleJson)
            : default(Recipe);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// Update an existing recipe
        /// </summary>
        /// <remarks>Update an existing recipe by Id</remarks>
        /// <param name="body">Update an existing recipe in the store</param>
        /// <response code="200">Successfully updated recipe.</response>
        /// <response code="400">Bad Request</response>
        /// <response code="404">Recipe not found</response>
        [HttpPut]
        [Route("/recipe")]
        [SwaggerOperation("UpdateRecipe")]
        [SwaggerResponse(statusCode: 200, type: typeof(Recipe), description: "Successfully updated recipe.")]
        public virtual IActionResult UpdateRecipe([FromBody] Recipe body)
        {
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(Recipe));

            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400);

            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404);
            string exampleJson = null;
            exampleJson = "{\n  \"dateCreated\" : \"2000-01-23T04:56:07.000+00:00\",\n  \"name\" : \"Chicken Tikka Masala\",\n  \"ingredients\" : [ {\n    \"amount\" : \"todo\",\n    \"name\" : \"Milk\"\n  }, {\n    \"amount\" : \"todo\",\n    \"name\" : \"Milk\"\n  } ],\n  \"id\" : 0,\n  \"source\" : \"From Crook to Crook\",\n  \"labels\" : [ {\n    \"name\" : \"Breakfast\"\n  }, {\n    \"name\" : \"Breakfast\"\n  } ]\n}";

            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<Recipe>(exampleJson)
            : default(Recipe);            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
